server {
    if ($host = www.cyberpi.tech) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name cyberpi.tech www.cyberpi.tech;

    # Force HTTP to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name cyberpi.tech www.cyberpi.tech;

    ssl_certificate /etc/letsencrypt/live/cyberpi.tech/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/cyberpi.tech/privkey.pem; # managed by Certbot

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }

    location /quickdraw/ {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /quickdraw/index.html;
    }

    location /chatbot/ {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /chatbot/index.html;
    }

    location /chatroom/ {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /chatroom/index.html;
    }
}
